apiVersion: v1
kind: Service
metadata:
  name: context-service
  namespace: {{ .Values.global.namespace | default "betterbooks" }}
  labels:
    app: context-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: context-service