-- Migration: Add Chapter Detection and AI Features
-- Created: 2025-01-08T00:00:00
-- Version: V004_20250108

-- +migrate Up
-- Chapter detection sessions to track AI analysis runs
CREATE TABLE IF NOT EXISTS chapter_detection_sessions (
    id TEXT PRIMARY KEY,
    book_id UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    detection_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total_chapters_detected INTEGER NOT NULL DEFAULT 0,
    detection_confidence DECIMAL(3,2) DEFAULT 0.00,
    processing_time_seconds DECIMAL(10,3),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chapter metadata for storing AI-generated information
CREATE TABLE IF NOT EXISTS chapter_metadata (
    chapter_id TEXT PRIMARY KEY REFERENCES book_chapters(id) ON DELETE CASCADE,
    metadata JSONB NOT NULL DEFAULT '{}',
    ai_generated_summary TEXT,
    ai_confidence DECIMAL(3,2) DEFAULT 0.00,
    key_topics TEXT[],
    sentiment_score DECIMAL(3,2),
    reading_difficulty INTEGER CHECK (reading_difficulty >= 1 AND reading_difficulty <= 10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Content summaries generated by AI for different granularities
CREATE TABLE IF NOT EXISTS ai_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content_type VARCHAR(50) NOT NULL, -- 'book', 'chapter', 'section'
    content_id TEXT NOT NULL, -- references the specific content (book_id, chapter_id, etc.)
    summary_type VARCHAR(50) NOT NULL, -- 'brief', 'detailed', 'key_points'
    summary_text TEXT NOT NULL,
    summary_metadata JSONB DEFAULT '{}',
    generated_by VARCHAR(50) DEFAULT 'ai_system',
    generation_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    quality_score DECIMAL(3,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE(content_type, content_id, summary_type)
);

-- AI-powered Q&A system for interactive book discussions
CREATE TABLE IF NOT EXISTS book_qa_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    session_name VARCHAR(200),
    context_chapter_ids TEXT[], -- chapters providing context for this session
    session_metadata JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Individual Q&A interactions within sessions
CREATE TABLE IF NOT EXISTS qa_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES book_qa_sessions(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    answer_text TEXT NOT NULL,
    context_used TEXT[], -- specific text segments used for context
    confidence_score DECIMAL(3,2),
    response_time_ms INTEGER,
    user_rating INTEGER CHECK (user_rating >= 1 AND user_rating <= 5),
    interaction_metadata JSONB DEFAULT '{}',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User reading behavior and preferences for adaptive recommendations
CREATE TABLE IF NOT EXISTS reading_behavior (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    chapter_id TEXT, -- references book_chapters(id), nullable for book-level behavior
    behavior_type VARCHAR(50) NOT NULL, -- 'reading_speed', 'pause_pattern', 'chapter_completion', etc.
    behavior_data JSONB NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_id UUID, -- groups behaviors from the same reading session
    
    INDEX idx_reading_behavior_user_book (user_id, book_id),
    INDEX idx_reading_behavior_type (behavior_type),
    INDEX idx_reading_behavior_timestamp (recorded_at)
);

-- AI-generated reading recommendations
CREATE TABLE IF NOT EXISTS reading_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recommended_book_id UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    recommendation_type VARCHAR(50) NOT NULL, -- 'similar_content', 'reading_level', 'genre_preference', etc.
    confidence_score DECIMAL(3,2) NOT NULL,
    reasoning TEXT,
    source_books UUID[], -- books that influenced this recommendation
    recommendation_metadata JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    
    UNIQUE(user_id, recommended_book_id, recommendation_type)
);

-- Book content analysis results for improved recommendations
CREATE TABLE IF NOT EXISTS book_analysis (
    book_id UUID PRIMARY KEY REFERENCES books(id) ON DELETE CASCADE,
    content_analysis JSONB NOT NULL DEFAULT '{}', -- themes, topics, sentiment, etc.
    reading_level INTEGER CHECK (reading_level >= 1 AND reading_level <= 10),
    estimated_reading_time_minutes INTEGER,
    genre_classification TEXT[],
    content_warnings TEXT[],
    target_audience VARCHAR(100),
    language_complexity DECIMAL(3,2),
    analysis_version VARCHAR(20) DEFAULT '1.0',
    analyzed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for AI and chapter detection features
CREATE INDEX IF NOT EXISTS idx_chapter_detection_sessions_book_id ON chapter_detection_sessions(book_id);
CREATE INDEX IF NOT EXISTS idx_chapter_detection_sessions_timestamp ON chapter_detection_sessions(detection_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_chapter_metadata_topics ON chapter_metadata USING gin(key_topics);
CREATE INDEX IF NOT EXISTS idx_chapter_metadata_confidence ON chapter_metadata(ai_confidence DESC);

CREATE INDEX IF NOT EXISTS idx_ai_summaries_content ON ai_summaries(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_ai_summaries_type ON ai_summaries(summary_type);
CREATE INDEX IF NOT EXISTS idx_ai_summaries_timestamp ON ai_summaries(generation_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_book_qa_sessions_user_book ON book_qa_sessions(user_id, book_id);
CREATE INDEX IF NOT EXISTS idx_book_qa_sessions_active ON book_qa_sessions(is_active) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_qa_interactions_session ON qa_interactions(session_id);
CREATE INDEX IF NOT EXISTS idx_qa_interactions_confidence ON qa_interactions(confidence_score DESC);
CREATE INDEX IF NOT EXISTS idx_qa_interactions_timestamp ON qa_interactions(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_reading_recommendations_user ON reading_recommendations(user_id);
CREATE INDEX IF NOT EXISTS idx_reading_recommendations_active ON reading_recommendations(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_reading_recommendations_confidence ON reading_recommendations(confidence_score DESC);

CREATE INDEX IF NOT EXISTS idx_book_analysis_genre ON book_analysis USING gin(genre_classification);
CREATE INDEX IF NOT EXISTS idx_book_analysis_reading_level ON book_analysis(reading_level);
CREATE INDEX IF NOT EXISTS idx_book_analysis_target_audience ON book_analysis(target_audience);

-- Add some useful functions for AI features
CREATE OR REPLACE FUNCTION update_chapter_metadata_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_chapter_metadata_timestamp
    BEFORE UPDATE ON chapter_metadata
    FOR EACH ROW
    EXECUTE FUNCTION update_chapter_metadata_timestamp();

CREATE OR REPLACE FUNCTION update_ai_summaries_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_ai_summaries_timestamp
    BEFORE UPDATE ON ai_summaries
    FOR EACH ROW
    EXECUTE FUNCTION update_ai_summaries_timestamp();

-- Function to get chapter at specific timestamp
CREATE OR REPLACE FUNCTION get_chapter_at_timestamp(p_book_id UUID, p_timestamp INTEGER)
RETURNS TABLE (
    chapter_id TEXT,
    chapter_number INTEGER,
    title VARCHAR(300),
    start_time INTEGER,
    end_time INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        bc.id,
        bc.chapter_number,
        bc.title,
        bc.start_time_seconds,
        bc.end_time_seconds
    FROM book_chapters bc
    WHERE bc.book_id = p_book_id 
        AND bc.start_time_seconds <= p_timestamp 
        AND bc.end_time_seconds >= p_timestamp
    ORDER BY bc.chapter_number
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate reading statistics
CREATE OR REPLACE FUNCTION calculate_user_reading_stats(p_user_id UUID, p_book_id UUID DEFAULT NULL)
RETURNS TABLE (
    total_books INTEGER,
    total_chapters INTEGER,
    total_reading_time_minutes INTEGER,
    average_reading_speed_wpm INTEGER,
    completion_rate DECIMAL(5,2)
) AS $$
BEGIN
    RETURN QUERY
    WITH reading_stats AS (
        SELECT 
            COUNT(DISTINCT urp.book_id) as book_count,
            COUNT(DISTINCT bc.id) as chapter_count,
            COALESCE(SUM(urp.total_listening_time), 0) / 60 as total_minutes,
            AVG(urp.completion_percentage) as avg_completion
        FROM user_reading_progress urp
        LEFT JOIN book_chapters bc ON bc.book_id = urp.book_id
        WHERE urp.user_id = p_user_id
            AND (p_book_id IS NULL OR urp.book_id = p_book_id)
    )
    SELECT 
        rs.book_count::INTEGER,
        rs.chapter_count::INTEGER,
        rs.total_minutes::INTEGER,
        CASE 
            WHEN rs.total_minutes > 0 THEN (rs.chapter_count * 250 / rs.total_minutes)::INTEGER -- Estimate 250 words per chapter
            ELSE 0 
        END,
        COALESCE(rs.avg_completion, 0)::DECIMAL(5,2)
    FROM reading_stats rs;
END;
$$ LANGUAGE plpgsql;

-- +migrate Down
-- Drop functions
DROP FUNCTION IF EXISTS calculate_user_reading_stats(UUID, UUID);
DROP FUNCTION IF EXISTS get_chapter_at_timestamp(UUID, INTEGER);

-- Drop triggers
DROP TRIGGER IF EXISTS trigger_update_ai_summaries_timestamp ON ai_summaries;
DROP TRIGGER IF EXISTS trigger_update_chapter_metadata_timestamp ON chapter_metadata;

-- Drop functions for triggers
DROP FUNCTION IF EXISTS update_ai_summaries_timestamp();
DROP FUNCTION IF EXISTS update_chapter_metadata_timestamp();

-- Drop indexes
DROP INDEX IF EXISTS idx_book_analysis_target_audience;
DROP INDEX IF EXISTS idx_book_analysis_reading_level;
DROP INDEX IF EXISTS idx_book_analysis_genre;
DROP INDEX IF EXISTS idx_reading_recommendations_confidence;
DROP INDEX IF EXISTS idx_reading_recommendations_active;
DROP INDEX IF EXISTS idx_reading_recommendations_user;
DROP INDEX IF EXISTS idx_qa_interactions_timestamp;
DROP INDEX IF EXISTS idx_qa_interactions_confidence;
DROP INDEX IF EXISTS idx_qa_interactions_session;
DROP INDEX IF EXISTS idx_book_qa_sessions_active;
DROP INDEX IF EXISTS idx_book_qa_sessions_user_book;
DROP INDEX IF EXISTS idx_ai_summaries_timestamp;
DROP INDEX IF EXISTS idx_ai_summaries_type;
DROP INDEX IF EXISTS idx_ai_summaries_content;
DROP INDEX IF EXISTS idx_chapter_metadata_confidence;
DROP INDEX IF EXISTS idx_chapter_metadata_topics;
DROP INDEX IF EXISTS idx_chapter_detection_sessions_timestamp;
DROP INDEX IF EXISTS idx_chapter_detection_sessions_book_id;

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS book_analysis;
DROP TABLE IF EXISTS reading_recommendations;
DROP TABLE IF EXISTS reading_behavior;
DROP TABLE IF EXISTS qa_interactions;
DROP TABLE IF EXISTS book_qa_sessions;
DROP TABLE IF EXISTS ai_summaries;
DROP TABLE IF EXISTS chapter_metadata;
DROP TABLE IF EXISTS chapter_detection_sessions;