apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "context-service.fullname" . }}
  labels:
    app: {{ include "context-service.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "context-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "context-service.name" . }}
    spec:
      containers:
        - name: context-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url
