apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [server]
    root_url = {{ .Values.config.server.root_url }}
    domain = {{ .Values.config.server.domain }}

    [security]
    admin_user = {{ .Values.config.security.admin_user }}
    admin_password = {{ .Values.config.security.admin_password }}
    allow_embedding = {{ .Values.config.security.allow_embedding }}
    cookie_secure = {{ .Values.config.security.cookie_secure }}

    [auth.anonymous]
    enabled = {{ .Values.config.auth.anonymous.enabled }}

    [dashboards]
    default_home_dashboard_path = {{ .Values.config.dashboards.default_home_dashboard_path }}

    [log]
    mode = console
    level = info

    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    {{- range .Values.datasources }}
    - name: {{ .name }}
      type: {{ .type }}
      access: {{ .access }}
      url: {{ .url }}
      isDefault: {{ .isDefault }}
      editable: {{ .editable }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-dashboards-provider
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    {{- range .Values.dashboardProviders }}
    - name: {{ .name }}
      orgId: {{ .orgId }}
      folder: '{{ .folder }}'
      type: {{ .type }}
      disableDeletion: {{ .disableDeletion }}
      updateIntervalSeconds: {{ .updateIntervalSeconds }}
      allowUiUpdates: {{ .allowUiUpdates }}
      options:
        path: {{ .options.path }}
    {{- end }}