# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: context_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'context_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontext_service.proto\x12\x13\x62\x65tterbooks.context\"0\n\x0e\x43ontextRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"\"\n\x0f\x43ontextResponse\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t2i\n\x0e\x43ontextService\x12W\n\nGetContext\x12#.betterbooks.context.ContextRequest\x1a$.betterbooks.context.ContextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTREQUEST']._serialized_start=46
  _globals['_CONTEXTREQUEST']._serialized_end=94
  _globals['_CONTEXTRESPONSE']._serialized_start=96
  _globals['_CONTEXTRESPONSE']._serialized_end=130
  _globals['_CONTEXTSERVICE']._serialized_start=132
  _globals['_CONTEXTSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
