# Generated file from protoc

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_gateway.proto\x12\x0f\x62\x65tterbooks.llm\"\"\n\x0fGenerateRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\" \n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2a\n\nLLMGateway\x12S\n\x0cGenerateText\x12 .betterbooks.llm.GenerateRequest\x1a!.betterbooks.llm.GenerateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=38
  _globals['_GENERATEREQUEST']._serialized_end=72
  _globals['_GENERATERESPONSE']._serialized_start=74
  _globals['_GENERATERESPONSE']._serialized_end=106
  _globals['_LLMGATEWAY']._serialized_start=108
  _globals['_LLMGATEWAY']._serialized_end=205
# @@protoc_insertion_point(module_scope)
