# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tts_service.proto\x12\x0f\x62\x65tterbooks.tts\"!\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x12SynthesizeResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32i\n\nTTSService\x12[\n\x10SynthesizeSpeech\x12\".betterbooks.tts.SynthesizeRequest\x1a#.betterbooks.tts.SynthesizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=38
  _globals['_SYNTHESIZEREQUEST']._serialized_end=71
  _globals['_SYNTHESIZERESPONSE']._serialized_start=73
  _globals['_SYNTHESIZERESPONSE']._serialized_end=108
  _globals['_TTSSERVICE']._serialized_start=110
  _globals['_TTSSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
